[workspace]
resolver = "2"
members = [
    "json",
    "examples",
]

[workspace.package]
name = "my_parsing_lib"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = "1"
serde_json = "1"
typify = "0.0.16"
quick-xml = "0.31.0"
